services:
  base:
    build:
      tags:
        - "asset_register_base:prod"
    pull_policy: build
    image: "asset_register_base:prod"

  gql:
    build:
      context: "./workspaces/backend/gql"
    environment:
      GQL_SERVER_PORT: ${GQL_SERVER_PORT}
      DATABASE_HOST: db
      DATABASE_PORT: ${DB_PORT}
      DATABASE_DATABASE: ${DB_DATABASE}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      ENABLE_DB_LOGGING: ${ENABLE_DB_LOGGING}
    ports:
      - "${GQL_PUBLISHED_PORT}:${GQL_SERVER_PORT}"
    depends_on:
      - base
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PUBLISHED_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
